# Generated by Django 3.2.5 on 2021-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210723_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='invoices',
            field=models.ManyToManyField(related_name='invoice_guest', through='api.InvoiceGuest', to='api.Guest'),
        ),
    ]
