# Generated by Django 3.2.5 on 2021-07-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210723_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
                ('status_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservationstatuscalalog')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ManyToManyField(through='api.ReservationStatusEvent', to='api.ReservationStatusCalalog'),
        ),
    ]
