# Generated by Django 3.2.5 on 2021-07-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210723_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceguest',
            options={'verbose_name': 'invoice_guest'},
        ),
    ]
