# Generated by Django 3.2.5 on 2021-07-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_invoiceguest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceguest',
            options={},
        ),
        migrations.AlterModelTable(
            name='invoiceguest',
            table='invoice_guest',
        ),
    ]
