# Generated by Django 3.2.5 on 2021-07-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210723_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceguest',
            options={'verbose_name': 'invoice_guest'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.AlterUniqueTogether(
            name='reservationstatusevent',
            unique_together={('reservation', 'status_catalog')},
        ),
        migrations.AlterModelTable(
            name='guest',
            table='guests',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
        migrations.AlterModelTable(
            name='reservationstatuscalalog',
            table='reservation_status_calalog',
        ),
        migrations.AlterModelTable(
            name='reservationstatusevent',
            table='reservation_status_event',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roomreserved',
            table='room_reserved',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_types',
        ),
    ]
