# Generated by Django 3.2.5 on 2021-07-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210723_0608'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservationstatuscalalog',
            table='reservation_status_calalogs',
        ),
    ]
